# Generated by Django 3.2 on 2021-04-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhamma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhamma',
            name='title',
            field=models.CharField(max_length=301),
        ),
    ]
