# Generated by Django 3.2 on 2021-04-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhamma', '0002_alter_dhamma_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhamma',
            name='title',
            field=models.CharField(max_length=303),
        ),
    ]
