# Generated by Django 3.2 on 2021-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhamma', '0005_remove_dhamma_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhamma',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
