# Generated by Django 3.2 on 2021-04-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhamma', '0006_dhamma_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhamma',
            name='sadhu',
        ),
    ]
